# base image
FROM mjawwad/redhat8-vault

# set vault version
ENV VAULT_VERSION 1.6.0

# create a new directory
RUN mkdir /vault

# download dependencies
RUN yum install wget unzip -y

# download and set up vault
RUN wget --quiet --output-document=/tmp/vault.zip https://releases.hashicorp.com/vault/1.6.0/vault_1.6.0_linux_amd64.zip && \
    unzip /tmp/vault.zip -d /vault && \
    rm -f /tmp/vault.zip && \
    chmod +x /vault

# update PATH
ENV PATH="PATH=$PATH:$PWD/vault"

# add the config file
COPY ./config/vault-config.json /vault/config/vault-config.json
 
# expose port 8200
EXPOSE 8200

#Copy Script
COPY ./config/vault-secert.sh /usr/bin/vault-secert.sh
COPY ./config/keys.log /vault/config/keys.log

ENTRYPOINT [""]
